### ISSUE TITLE
irc quit/leave command spits error

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/dIRCBot#1]
`/ex irc quit ircchannel@irc.esper.net`
http://mcmonkey.org/haste/17070

`/ex irc leave ircchannel@irc.esper.net`
http://mcmonkey.org/haste/17072

Makes it impossible to fully quit the IRC without restarting the server and terminating connection entirely

**Comment by mcmonkey4eva** [comment]
Learn how to use dIRCBot please.

`ircchannel@server#channel`
OR
`ircserver@server`

Pick one, use it as needed.

**Comment by Fortifier42** [comment]
More docs then

**Comment by mcmonkey4eva** [comment]
Ima make a video or something on it eventually.

**Comment by Fortifier42** [comment]
That is the only issue I had with it. Can't leave IRC server.
