### ISSUE TITLE
occasional output of random time out message

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/dIRCBot#4]
```
[21:48:36 INFO]: IRC Error
[21:48:36 WARN]: java.lang.RuntimeException: IRC ping timed out!
[21:48:36 WARN]:        at org.mcmonkey.dIRCBot.IRCServerHolder.run(IRCServerHolder.java:88)
```

**Comment by mcmonkey4eva** [comment]
That means the bot died (through no fault of our own, generally it's either your network or the IRC server). It automatically restarts at that point, in theory.

**Comment by Fortifier42** [comment]
I wasn't connected to any irc at the time.. It was idle on my server with no connections

**Comment by mcmonkey4eva** [comment]
You were connected to /something/, even if you didn't intend to be

**Comment by Fortifier42** [comment]
@mcmonkey4eva my server had only just started... O.o

**Comment by mcmonkey4eva** [comment]
I unno what to tell you - perhaps some old autoconnect script you forgot about. Look at the relevant code mate, that's deep in the 'already connected to a server' section
